services:
  - type: web
    name: disease-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"